version: '3'
services:
  redis:
    image: "redis:alpine"
    networks:
      - chatnet

  node1:
    build: .
    ports:
      - "3001:3000"
    environment:
      - REDIS_HOST=redis
    networks:
      - chatnet

  node2:
    build: .
    ports:
      - "3002:3000"
    environment:
      - REDIS_HOST=redis
    networks:
      - chatnet

  node3:
    build: .
    ports:
      - "3003:3000"
    environment:
      - REDIS_HOST=redis
    networks:
      - chatnet

networks:
  chatnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
