version: '3'
services:
  director:
    build:
      context: ./director
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      chatnet:
        ipv4_address: 172.30.0.2

  node1:
    build:
      context: ./node
      dockerfile: Dockerfile
    environment:
      - PORT=4000
      - DIRECTOR_URL=http://172.30.0.2:3000
      - NODE_HOST=172.30.0.3
      - PUBLIC_HOST=localhost
    depends_on:
      - director
    ports:
      - "4000:4000"
    networks:
      chatnet:
        ipv4_address: 172.30.0.3

  node2:
    build:
      context: ./node
      dockerfile: Dockerfile
    environment:
      - PORT=4001
      - DIRECTOR_URL=http://172.30.0.2:3000
      - NODE_HOST=172.30.0.4
      - PUBLIC_HOST=localhost
    depends_on:
      - director
    ports:
      - "4001:4001"
    networks:
      chatnet:
        ipv4_address: 172.30.0.4

  node3:
    build:
      context: ./node
      dockerfile: Dockerfile
    environment:
      - PORT=4002
      - DIRECTOR_URL=http://172.30.0.2:3000
      - NODE_HOST=172.30.0.5
      - PUBLIC_HOST=localhost
    depends_on:
      - director
    ports:
      - "4002:4002"
    networks:
      chatnet:
        ipv4_address: 172.30.0.5

networks:
  chatnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16
